### ISSUE TITLE
Some asset can not be downloaded

### ISSUE THREAD

**Issue by cosmosdingli** [diskuv/dkml-installer-ocaml#101]
I installed it in an aws ec2 windows server which network is restricted partly.  
So I got an error when download ocaml-opam-repo-4.14.0.zip , how can I resolve it except by fix network problem.
Such as I download ocaml-opam-repo-4.14.0.zip form other pc , and bring it to the target server.
Help me please, thank you.

**Comment by jonahbeckford** [comment]
It is theoretically possible to make a fully offline installation ... I haven't done that for a while, and I'm not sure it would work for you. (And it will take time on my part!).

Perhaps we can chat first. Do you have a preferred way to communicate? I can do:
1. https://discord.com/channels/436568060288172042/1138866520001351680 and send a message to `@jonahb`. Also tell me when you will be there by replying to this issue.
2. https://calendly.com/diskuv/30-minute-dkml-installation

I am in the Pacific time zone. Mon-Thurs 8am-10am Japan Standard Time works for me.

**Comment by jonahbeckford** [comment]
No response yet. Open if needed.
