### ISSUE TITLE
new 2.2.1 install, still not finding advapi32.lib and uuid.lib

### ISSUE THREAD

**Issue by Drakken** [diskuv/dkml-installer-ocaml#103]
after running (& opam env --switch=playground --set-switch) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }

(dune isn't visible in the local switch)

\> opam switch
\#  switch         compiler
          description
   C:\Users\User
          dkml-host-abi-windows_x86_64.1,dkml-target-abi-windows_x86_64.1,msys2.0.1.0+dkml,msys2-clang64.1,ocaml-system.4.14.2
          ocaml-system = 4.14.2 & conf-withdkml & dkml-host-abi-windows_x86_64 & msys2-clang64 & host-arch-x86_64
→  playground     msys2.0.1.0+dkml,msys2-clang64.1,ocaml-system.4.14.2
          ocaml-system = 4.14.2 & conf-withdkml & msys2-clang64 & host-arch-x86_64

[NOTE] Current switch is set globally and through the OPAMSWITCH variable.
       Thus, the local switch found at C:\Users\User was ignored.

\> dune build
[0;1mFile "lib/dune", line 1, characters 0-23:[0m
1 | (library
2 |  (name blote))
** Fatal error: Cannot find file "uuid.lib"
[1mFile "caml_startup", line 1[0m:
[1;31mError[0m: Error during linking (exit code 2)
[0;1mFile "bin/dune", line 3, characters 7-11:[0m
3 |  (name main)
           ^^^^
** Fatal error: Cannot find file "advapi32.lib"
[1mFile "caml_startup", line 1[0m:
[1;31mError[0m: Error during linking (exit code 2)

**Comment by jonahbeckford** [comment]
Please use `opam exec -- dune build` instead. Basically put `opam exec --` in front of commands.

(That used to be the instructions on ocaml.org)

**Comment by Drakken** [comment]
Thank you.
