### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by denismaier** [diskuv/dkml-installer-ocaml#105]
Hi,
I've tried to uninstall DKML because I want to switch to the new OPAM based installation. When I run the uninstaller, I'm getting this error message:

```
FATAL [14b63c08]. The component 'offline-desktop-full' declares a dependency on 'staging-desktop-full' but that dependency is not available as a plugin. Check the following in order: 1) Has `dkml-component-staging-desktop-full` been added as an Opam (or findlib) dependency? 2) Does `dkml-component-staging-desktop-full` call [Registry.add_component] using [component_name="staging-desktop-full"]?
```

I must admit I'm a bit lost here. How can I uninstall DKML OCaml?

**Comment by jonahbeckford** [comment]
Use the first three steps of the release notes: https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.1#upgrading-from-versions-earlier-than-210.

Also see https://discuss.ocaml.org/t/ocaml-re-install-on-windows/15552/2?u=jbeckford.

Good luck!

**Comment by denismaier** [comment]
You mean I need to upgrade in order to uninstall?

**Comment by denismaier** [comment]
Oh. Now I see. Only last step is upgrade. I was looking under the wrong heading.

**Comment by denismaier** [comment]
Ok. That worked! Thank you again.
