### ISSUE TITLE
utop can't load Base library

### ISSUE THREAD

**Issue by F-Loyer** [diskuv/dkml-installer-ocaml#11]
With dune, I can compile a program which uses the Base library. But can't use the same library with utop.

```
PS D:\DiskuvProjets\essai> with-dkml utop   
│ Welcome to utop version 2.9.0 (using OCaml version 4.12.1)! │                                                                                                      
utop.exe: lambda-term(history): failed to lock file 'C:\Users\frede\AppData\Local\Programs\DiskuvOCaml\tools\MSYS2\home\frede\.utop-history': Une opération de verrouillage de fichier demandée ne peut pas être traitée en raison d’une plage d’octets non valide.
utop.exe: lambda-term(history):

Type #utop_help for help about using utop.

utop # #use "topfind";;
- : unit = ()Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

- : unit = ()
utop # #require "base";;
Cannot load required shared library dllbase_internalhash_types_stubs.
Reason: dllbase_internalhash_types_stubs.dll: L'opération a réussi.
.
Cannot load required shared library dllbase_stubs.
Reason: dllbase_stubs.dll: L'opération a réussi.
.
utop # Base.List.map;;Line 1:Error: Reference to undefined global `Base__List'
```
There is a DLL error while "requiring" base (and the reason is a success !), then, the functions from the library are not available.

**Comment by jonahbeckford** [comment]
Sorry I didn't see this earlier! I missed the email notification.

There are two issues ... one you can fix, and one I can fix:

1. (You can fix). If you are in a switch directory and you have entered it with `for /f "tokens=*" %i in ('opam env --set-switch') do @%i` in the Command Prompt, then your `#require "base";;` should work. If it doesn't, try `opam install utop` first and then try again. See https://diskuv.gitlab.io/diskuv-ocaml/doc/BeyondBasics.html#learn-ocaml-a-first-project if my language about a "switch" is confusing.
2. (I can fix). It would be nice to get that `#require "base";;` to work _without_ a switch. So regardless I'll keep this open (although it may take a few versions before it is fixed).

If what I said in option `1` does not make sense, please use https://calendly.com/diskuv/60min-install to schedule a Zoom call. We'll likely need about 10-15 minutes.

**Comment by F-Loyer** [comment]
Ok, that works. Thanks a lot.

One useful think to know is to double the % when copying the for statement in a CMD file to ease the reinitialization of the environnement.

**Comment by jonahbeckford** [comment]
I think I need to give three different versions of the commands:
1. Command Prompt
2. CMD file
3. PowerShell

I'll keep this open to track that. Thanks!

**Comment by jonahbeckford** [comment]
The fix won't be in the next point release, but it will get in there.

**Comment by jonahbeckford** [comment]
Status update: This didn't make it in for https://github.com/diskuv/dkml-installer-ocaml/releases/tag/v1.1.0_r2 (1.1.0). The issue needs to stay open.

**Comment by jonahbeckford** [comment]
Interim results. The following gives a working `#require "base";;` ...

```
opam install --switch C:\Users\beckf\AppData\Local\Programs\DISKUV~1\dkml base
opam exec --switch C:\Users\beckf\AppData\Local\Programs\DISKUV~1\dkml utop
```

* The first command will be done automatically during installation (next release). Commit: https://github.com/diskuv/dkml-runtime-distribution/commit/db124b2fb018c1b58ab671363a4ff5f612389697
* The second command will need to be simplified. The global utop will need a shim
  so that the `lib/stublibs` of the `dkml` switch is added to the PATH.

**Comment by jonahbeckford** [comment]
Major release https://discuss.ocaml.org/t/ann-dkml-2-0-0-preview-release/12642 closes this.
