### ISSUE TITLE
Unbound module Stdlib

### ISSUE THREAD

**Issue by jonahbeckford** [diskuv/dkml-installer-ocaml#13]
Hello, I think I have the same problem. I tried running it without any anti-virus, but it did not change anything.
The error message seems to be the same, but before that I have : 
```
========= [TROUBLESHOOTING] ocaml-system-71408-2bcd70.out ===========

[ocaml-system-71408-2bcd70.out] File "command line", line 1:
[ocaml-system-71408-2bcd70.out] Error: Unbound module Stdlib

Scroll up to see the [TROUBLESHOOTING] logs that begin at the [START OF TROUBLESHOOTING] line
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: export DKML_TMP_PARENTDIR='/ [...]
```
`Error: Unbound module Stdlib` That problem seems to be linked to incorrect version of compiler corresponding to the code.

( There is another problem afterwards when I try to re-install the code (but that is another problem) ; 

```
2022-11-09T20:20:56.921Z Cleaning directory C:\Users\louis\AppData\Local\Programs\DiskuvOCaml\0 ...
Set-ItemProperty : Impossible de définir l’attribut, car les attributs ne sont pas pris en charge. Seuls les attributs suivants peuvent être définis :
Archive, Hidden, Normal, ReadOnly ou System.
Au caractère C:\Users\louis\AppData\Local\Temp\7z4A04CEBC\sg\network-ocamlcompiler\windows_x86_64\SingletonInstall\Deployers\Deployers.psm1:508 : 13
+             Set-ItemProperty -Path $_.FullName -Name Attributes -Valu ...
+          
```

)

_Originally posted by @LouisClt in https://github.com/diskuv/dkml-installer-ocaml/issues/9#issuecomment-1310007083_

**Comment by jonahbeckford** [comment]
(I used a new issue since the error looks very different)

Can you:
1. Erase `C:\Users\louis\AppData\Local\Programs\DiskuvOCaml` using the File Explorer
2. Open a Command Prompt and type `ocamlc -config`. Hopefully that failed! If it didn't fail, please copy and paste the output into this issue, and do not go to step 3 below.
3. Try to reinstall. If the reinstall does not work, you can setup a Zoom video call at https://calendly.com/diskuv/60min-install

**Comment by LouisClt** [comment]
Thanks for your support, sorry, I thought the issue was similar with the other.
With your indications I was eventually able to install successfully diskuv. The problem was, it seems, that I had a previous installation of CamlLight that had defined the "CAMLLIB" env variable. This variable seemed to interfere with the process of installing diskuv (notably OCaml compilations). Removing this variable seemed to have fixed the problem (I also uninstalled CamlLight but I think it was not necessary).

**Comment by jonahbeckford** [comment]
Do you think it should be safe just to delete the `CAMLLIB` environment variable if it exists at install time? I'm not that familiar with Caml Light.

**Comment by nojb** [comment]
> Do you think it should be safe just to delete the `CAMLLIB` environment variable if it exists at install time? I'm not that familiar with Caml Light.

Note that `CAMLLIB` is accepted as a synonym for `OCAMLLIB` to specify the standard library directory in current-date OCaml:

https://github.com/ocaml/ocaml/blob/dc0ab7f25841daa77c3c92d90dcfa8ea6db2621c/utils/config.common.ml#L22-L29

**Comment by jonahbeckford** [comment]
To be clear, I don't think there is anything wrong with setting `CAMLLIB` and/or `OCAMLLIB` inside your opam switches with the [setenv clause](https://opam.ocaml.org/doc/Manual.html#opamfield-setenv). The real problem is setting them globally as environment variables which will wreck havoc on almost all opam switches. @nojb Please tell me if there is a legitimate edge use case I'm missing.

Really it boils down to two choices:
1. Fail the installation immediately if either `CAMLLIB` or `OCAMLLIB` are in the environment.
2. Respect the intent of the user who chose to install a new OCaml onto their machine ... they want OCaml to work

I'm strongly leaning towards choice `2` (which means removing both `CAMLLIB` and `OCAMLLIB` if the installer sees them in the environment) because the DKML distribution is geared towards ease of use, and it is conventional for installers to remove "previous" installations (which Caml Light is), and I have yet to hear a legit reason why they should be in the environment. Of course I'll back up the environment variables (ex. rename `CAMLLIB` to `CAMLLIB_ORIG`).

**Comment by nojb** [comment]
> @nojb Please tell me if there is a legitimate edge use case I'm missing.

Not that I know of. Your 2. seems reasonable.

**Comment by LouisClt** [comment]
I am no expert in CamlLight either, but after a bit of testing, it does not seem CamlLight really needs to have the "CAMLLIB" env variable set to work correctly (at least when I call some basic functions from the standard library).
So removing/renaming this variable seems fine to me (maybe put a warning when you do it...).

**Comment by jonahbeckford** [comment]
Okay. The fix won't be in the next point release, but it will get in there.

- [ ] Rename `CAMLLIB` to `CAMLLIB_ORIG<ver>` and `OCAMLLIB_ORIG<ver>`. (`<ver>` is the DKML version, like `1_0_1`)

**Comment by jonahbeckford** [comment]
The fix is available in https://github.com/diskuv/dkml-installer-ocaml/releases/tag/v1.1.0_r2

Re-open if this is still an issue.
