### ISSUE TITLE
Can you provide an offline installer out of the box?

### ISSUE THREAD

**Issue by fenginsc** [diskuv/dkml-installer-ocaml#15]
Thank you very much for your work but currently the installer is networked but there are some issues as I already have the visual studio compiler suite as well as git for windows but it seems to duplicate the installation. 
If you could provide an out of the box installer that installs offline without downloading anything I think it would be easier to use.
The installer I think should be related to the Ocaml version so that the user can install the specified version of Ocaml offline, I think you could consider using WiX Toolset or other software to generate the installer.

**Comment by jonahbeckford** [comment]
> I already have the visual studio compiler suite

If you have a Visual Studio installation that is fully compatible with OCaml (ex. https://diskuv.gitlab.io/diskuv-ocaml/doc/AdvancedInstalls/WindowsAdministrator.html#using-an-existing-visual-studio-installation) then it will not install a new Visual Studio

> as well as git for windows

It will not install Git for Windows if you already have Git (unless you have a very very old version)

> the installer is networked

Yes, you need internet access. Can you tell me how that caused or is causing problems for you? Thanks

**Comment by fenginsc** [comment]
> > I already have the visual studio compiler suite
> 
> If you have a Visual Studio installation that is fully compatible with OCaml (ex. https://diskuv.gitlab.io/diskuv-ocaml/doc/AdvancedInstalls/WindowsAdministrator.html#using-an-existing-visual-studio-installation) then it will not install a new Visual Studio
> 
> > as well as git for windows
> 
> It will not install Git for Windows if you already have Git (unless you have a very very old version)
> 
> > the installer is networked
> 
> Yes, you need internet access. Can you tell me how that caused or is causing problems for you? Thanks

I have several computers that need to be installed, and my network download speed is not very fast, so it is very troublesome to download and install online every time, and it may take a long time. If there is an offline one-click installation package, it will let me Install without a network, and the offline installation package is usually bundled with a specific version, which allows me to install the specified version, such as the installation package of java-jdk and the installation package of nodejs, they all do this, thank you.

**Comment by jonahbeckford** [comment]
Marking a fully offline installer as WONTFIX. Part of the installation is Visual Studio, and Microsoft licensing does not allow bundling the entire Visual Studio into our own installer. Even if Visual Studio were not an issue, this feature request has marginal value.
