### ISSUE TITLE
dkml install alongside mys2

### ISSUE THREAD

**Issue by denismaier** [diskuv/dkml-installer-ocaml#16]
Hi,
IIUC, the DKML installer seems to be the prefered way to install ocaml on Windows. However, this methods seems to fail if you have installed msys2 locally. Is that possible somehow? Or should I better just wait for the next opam version?

**Comment by jonahbeckford** [comment]
Can you say what your error was?

*I have one standalone MSYS2 installation on top of the embedded (ie. transparent) MSYS2 installations inside Git for Windows and vcpkg and DKML. Having your own MSYS2 installation should not be a problem*

**Comment by denismaier** [comment]
I'm getting the following error message:

> FATAL [8b5571d0]. Detected that the setup program has been called inside a Cygwin or MSYS2 environment. In particular, C:\msys\usr\bin\cygpath.exe was available in the PATH. Since the setup program uses its own MSYS2 environment, and since MSYS2 does not support one MSYS2 or Cygwin environment calling another MSYS2 environment, it is highly probable the installation will fail. Please rerun the setup program directly from a Command Prompt, PowerShell, the File Explorer or directly from the browser Downloads if you downloaded it. Do not use Git Bash (part of Git for Windows) or anything else that contains an MSYS2 environment.

However, I've called the installer directly from a Command Prompt. (But msys2 is indeed in my path.)

**Comment by jonahbeckford** [comment]
Ah ... yes, if you have MSYS2 in your PATH you won't be able to use the DKML installer. To be honest, you will likely (at some point) start experiencing problems with Git for Windows, vcpkg and anything else that embeds MSYS2.

There is nothing that can be done about installing multiple versions of MSYS2; it is a limitation of MSYS2 and Cygwin. Waiting for the next version of opam is not going to change that problem.

---

If you want to install a non-system wide version of Diskuv OCaml that uses your own copy of MSYS2, that is somewhat supported but only for advanced users (which it seems you are if you have your own copy of MSYS2!).

* There are instructions for that at https://github.com/diskuv/dkml-workflows#windows-pc-backend, and a full example at https://github.com/diskuv/dkml-workflows-regular-example#readme.
* A pre-requisite is that you have to have a version of Visual Studio 2019 on your machine. https://diskuv.gitlab.io/diskuv-ocaml/doc/AdvancedInstalls/WindowsAdministrator.html#using-an-existing-visual-studio-installation has the precise details
* The only issue is that while I provided a zillion command line options for dkml-workflow's standalone script `setup-dkml-windows_x86_64.ps1`, I didn't provide an option to specify your own MSYS2 directory! You would have to wait until I do that (which is going to take at least a few weeks before I have bandwidth for that), or just edit the script yourself to rename all the `msys64\` with `C:\msys\`.

The flow would be something like the following in PowerShell (do not type in the `$` line beginnings):

```console
$ git clone https://github.com/diskuv/dkml-workflows-regular-example.git
$ cd dkml-workflows-regular-example

$ # EDIT: ci\setup-dkml\pc\setup-dkml-windows_x86_64.ps1
... rename all msys64\ to C:\msys\

$ & ci\setup-dkml\pc\setup-dkml-windows_x86_64.ps1
...
Finished setup.

To continue your testing, run in PowerShell:
  $env:CHERE_INVOKING = "yes"
  $env:MSYSTEM = "CLANG64"
  $env:dkml_host_abi = "windows_x86_64"
  $env:abi_pattern = "win32-windows_x86_64"
  $env:opam_root = "$PWD\.ci\o"
  $env:exe_ext = ".exe"

Now you can use 'opamrun' to do opam commands like:

  C:\msys\usr\bin\bash -lc 'PATH="$PWD/.ci/sd4/opamrun:$PATH"; opamrun install XYZ.opam'
  C:\msys\usr\bin\bash -lc 'PATH="$PWD/.ci/sd4/opamrun:$PATH"; opamrun -it exec -- bash'
  C:\msys\usr\bin\bash -lc 'PATH="$PWD/.ci/sd4/opamrun:$PATH"; opamrun exec -- sh ci/build-test.sh'
```

Those above steps would give you one local opam switch.

**Comment by denismaier** [comment]
Hmm, ok. I'll have a look. But maybe it could be easier to install ocaml in wsl2? That seems not to be recommended, but I don't really understand why. Do you know what would be the downsides of that approach?

**Comment by jonahbeckford** [comment]
You can definitely install OCaml in WSL2. The disadvantage is that the binaries you generate will be for Linux not Windows. The advantage is that OCaml on Linux is very well supported. If you are comfortable with that limitation (ex. you are just using OCaml for educational purposes, to try it out, etc.), WSL2 will be perfect.

---

If WSL2 is not a good choice for you, perhaps you can tell me why MSYS2 is in your PATH? (I can think of a couple reasons, but it is better for me not to guess). It might help prioritize making a variation of DKML that works with existing MSYS2 installations.

#### Also: Why to avoid putting MSYS2 in PATH

Are you aware that MSYS2's `link.exe` conflicts with Visual Studio's `link.exe`? That is, the default MSYS2 installation has [`/usr/bin/link.exe`](https://packages.msys2.org/package/coreutils?repo=msys&variant=x86_64) while whenever Visual Studio tools will modify the PATH to include Microsoft's C linker (ex. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\link.exe`).

**Comment by jonahbeckford** [comment]
Closing as resolved by using WSL2.
