### ISSUE TITLE
Windows install failure due to syntax error?

### ISSUE THREAD

**Issue by WillHolbrook** [diskuv/dkml-installer-ocaml#18]
When I run the installer I get the following output

2022-12-02T13:55:10.882Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\0 clone https://github.com/thekid/inotify-win.git
Cloning into 'inotify-win'...
2022-12-02T13:55:11.803Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\0\inotify-win -c advice.detachedHead=false checkout 36d18f3dfe042b21d7136a1479f08f0d8e30e2f9
HEAD is now at 36d18f3 Merge branch 'master' of github.com:thekid/inotify-win
2022-12-02T13:55:11.848Z [Win32] C:\Windows\system32\cmd.exe /c call "C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\0\inotify-win\compile.bat"

C:\Users\calga\AppData\Local\Temp\7z189C762C>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\0\inotify-win\inotifywait.exe" "C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\0\inotify-win\src\*.cs"
The syntax of the command is incorrect.
Setup did not complete because an error occurred.
Win32 command failed! Exited with 255. Command was: C:\Windows\system32\cmd.exe /c call "C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\0\inotify-win\compile.bat".

at Invoke-Win32CommandWithProgress, C:\Users\calga\AppData\Local\Temp\7z189C762C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 738
at <ScriptBlock>, C:\Users\calga\AppData\Local\Temp\7z189C762C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 866
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\calga\AppData\Local\Programs\DISKUV\~1\0\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\calga\AppData\Local\Temp\7z189C762C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\calga\AppData\Local\Programs\DISKUV\~1
                                             -MSYS2Dir
                                             C:\Users\calga\AppData\Local\Programs\DISKUV\~1\tools\MSYS2
                                             -OpamBinDir
                                             C:\Users\calga\AppData\Local\Temp\PA6DE1\~1\opam
                                             -DkmlPath
                                             C:\Users\calga\AppData\Local\Temp\7Z189C\~1\sg\NETWOR\~1\WINDOW\~1\dkmldir
                                             -DkmlHostAbi windows_x86_64
                                             -TempParentPath
                                             C:\Users\calga\AppData\Local\Temp\PA6DE1\~1
                                             -SkipProgress

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                                                    C:\Users\calga\AppData\Local\Temp\7z189C762C\bin\dkml-install-user-runner.exe
                                                                      install-user-network-ocamlcompiler
                                                                      --verbosity=info --color=always
                                                                      --prefix
                                                                      C:\Users\calga\AppData\Local\Programs\DiskuvOCaml
                                                                      --staging-files
                                                                      C:\Users\calga\AppData\Local\Temp\7z189C762C\sg

                         >>> A transient failure occurred. <<<

****

And the log file has the following message

2022-12-02T13:55:10.877Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\calga\AppData\Local\Temp\PA6DE1~1\0 clone https://github.com/thekid/inotify-win.git
Cloning into 'inotify-win'...
2022-12-02T13:55:11.798Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\calga\AppData\Local\Temp\PA6DE1~1\0\inotify-win -c advice.detachedHead=false checkout 36d18f3dfe042b21d7136a1479f08f0d8e30e2f9
HEAD is now at 36d18f3 Merge branch 'master' of github.com:thekid/inotify-win
2022-12-02T13:55:11.845Z [Win32] C:\Windows\system32\cmd.exe /c call "C:\Users\calga\AppData\Local\Temp\PA6DE1~1\0\inotify-win\compile.bat"

C:\Users\calga\AppData\Local\Temp\7z189C762C>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\calga\AppData\Local\Temp\PA6DE1~1\0\inotify-win\inotifywait.exe" "C:\Users\calga\AppData\Local\Temp\PA6DE1~1\0\inotify-win\src\*.cs" 
The syntax of the command is incorrect.

**Comment by jonahbeckford** [comment]
Can you ...

#### Repair your Visual Studio installation

1. Press the Windows key and then type in `Visual Studio Installer`. Run that.
2. Beside the "Visual Studio Build Tools 2019" installation you will see a `More` dropdown. Click the "Repair" button.

#### Re-install DKML

1. Run the uninstaller at https://github.com/diskuv/dkml-installer-ocaml/releases/download/v1.0.1/uninstall-diskuv-ocaml-windows_x86_64-1.0.1.exe
2. Rerun the installer at https://github.com/diskuv/dkml-installer-ocaml/releases/download/v1.0.1/setup-diskuv-ocaml-windows_x86_64-1.0.1.exe

Try that and reply in this ticket how it goes.

**Comment by eclairevoyant** [comment]
I was getting the same error on my end. I tried the steps listed above, and this is what I see:

```
windows_install.bc: [INFO] Verified 66 of 66 MB
windows_install.bc: [INFO] Running command: C:\Users\myself\AppData\Local\Temp\path_eval_1d29d9\msys2.exe
                                              -y
                                              -oC:\Users\myself\AppData\Local\Programs\DiskuvOCaml\tools\

7-Zip SFX 21.03 ZS v1.5.0 R2 (x64) : Copyright (c) 1999-2021 Igor Pavlov, 2016-2021 Tino Reichardt : 2021-10-05

Extracting archive: C:\Users\myself\AppData\Local\Temp\path_eval_1d29d9\msys2.exe
--
Path = C:\Users\myself\AppData\Local\Temp\path_eval_1d29d9\msys2.exe
Type = 7z

Everything is Ok
windows_install.bc: [INFO] C:\Users\myself\AppData\Local\Temp\path_eval_1d29d9\msys2.exe ran successfully
FATAL [54c34807]. move C:\Users\myself\AppData\Local\Programs\DiskuvOCaml\tools\msys64 to C:\Users\myself\AppData\Local\Programs\DiskuvOCaml\tools\MSYS2: Permission denied

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                                                    C:\Users\myself\AppData\Local\Temp\7zF0804504\bin\dkml-install-user-runner.exe
                                                                      install-user-network-unixutils
                                                                      --verbosity=info --color=always
                                                                      --prefix
                                                                      C:\Users\myself\AppData\Local\Programs\DiskuvOCaml
                                                                      --staging-files
                                                                      C:\Users\myself\AppData\Local\Temp\7zF0804504\sg

                         >>> A transient failure occurred. <<<



Press "y" and ENTER to exit the installer.
y
Exiting ...
```

I also tried in an elevated command prompt and it appeared to make no difference.
Would it make sense to install msys2 independently and then try to run this installer again? Or will this installer only use the bundled msys2 installation?

**Comment by jonahbeckford** [comment]
@eclairevoyant , after you run the uninstaller, can you use the File Explorer to delete the entire `C:\Users\myself\AppData\Local\Programs\DiskuvOCaml` directory? Run the installer again after that.

If that works please tell me; that will tell me that there is a bug in the uninstaller that can be fixed.

**Comment by jonahbeckford** [comment]
Re-open if there is still an issue. There is also a new installer at https://github.com/diskuv/dkml-installer-ocaml/releases/tag/v1.1.0_r2
