### ISSUE TITLE
Installer fails on Windows 11

### ISSUE THREAD

**Issue by enricogoi** [diskuv/dkml-installer-ocaml#20]
Note: Installer was run a admin.

Here is the failure:

C:\Users\enric\AppData\Local\Temp\PA01CD~1\0\DKMLW~1.QM9\opam-9748-ee3fee\index.tar.gz - Access is denied.
[ERROR] Could not update repository "default": Cannot remove C:\Users\enric\AppData\Local\Temp\PA01CD~1\0\DKMLW~1.QM9\opam-9748-ee3fee (error 145).
[ERROR] Initial repository fetch failed
rm: cannot remove '/c/Users/enric/AppData/Local/Temp/PA01CD~1/0/dkmlw.qM94s/opam-9748-ee3fee/index.tar.gz': Permission denied
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 1. Command was: export DKML_TMP_PARENTDIR='/c/Users/enric/AppData/Local/Temp/PA01CD~1/0' && export PATH='/c/Program Files/Git/cmd':"$PATH" && env DiskuvOCamlVarsVersion=2 DiskuvOCamlHome='/c/Users/enric/AppData/Local/Programs/DISKUV~1/0' DiskuvOCamlBinaryPaths='/c/Users/enric/AppData/Local/Programs/DISKUV~1/0/usr/bin:/c/Users/enric/AppData/Local/Programs/DISKUV~1/0/bin' DiskuvOCamlMSYS2Dir='/' DiskuvOCamlDeploymentId='v-1.0.1;ocaml-4.12.1;opam-2.2.0~alpha~dev;inotify-36d18f3dfe042b21d7136a1479f08f0d8e30e2f9;msys2-999CED2C8F5FF6A2;docker-B01818D2C9F9286A;pkgs-41F2F26E25F649A6;bins-A13EC471D2E2F24D;stubs-4E6958B274EAB043;toplevels-80941AA1C64DA259' DiskuvOCamlVersion='1.0.1' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR='/c/Users/enric/AppData/Local/Temp/7Z2A9F~1/sg/NETWOR~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop' 'C:\Users\enric\AppData\Local\Temp\7Z2A9F~1\sg\NETWOR~1\WINDOW~1\dkmldir\vendor\drd\src\unix\private\init-opam-root.sh' -p 'windows_x86_64' -o '/c/Users/enric/AppData/Local/Programs/DISKUV~1/0' -v '/c/Users/enric/AppData/Local/Programs/DISKUV~1/0'

at Invoke-MSYS2Command, C:\Users\enric\AppData\Local\Temp\7z2A9FDEBC\sg\network-ocamlcompiler\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 152
at Invoke-MSYS2CommandWithProgress, C:\Users\enric\AppData\Local\Temp\7z2A9FDEBC\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 822
at <ScriptBlock>, C:\Users\enric\AppData\Local\Temp\7z2A9FDEBC\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 1283
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

[Advanced] MSYS2 commands can be run with: C:\Users\enric\AppData\Local\Programs\DISKUV~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\enric\AppData\Local\Programs\DISKUV~1\0\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\enric\AppData\Local\Temp\7z2A9FDEBC\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\enric\AppData\Local\Programs\DISKUV~1
                                             -MSYS2Dir
                                             C:\Users\enric\AppData\L
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/10202156/setup-userprofile.full.log)
ocal\Programs\DISKUV~1\tools\MSYS2
                                             -OpamBinDir
                                             C:\Users\enric\AppData\Local\Temp\PA01CD~1\opam
                                             -DkmlPath
                                             C:\Users\enric\AppData\Local\Temp\7Z2A9F~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -DkmlHostAbi windows_x86_64
                                             -TempParentPath
                                             C:\Users\enric\AppData\Local\Temp\PA01CD~1
                                             -SkipProgress

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                                                    C:\Users\enric\AppData\Local\Temp\7z2A9FDEBC\bin\dkml-install-user-runner.exe
                                                                      install-user-network-ocamlcompiler
                                                                      --verbosity=info --color=always
                                                                      --prefix
                                                                      C:\Users\enric\AppData\Local\Programs\DiskuvOCaml
                                                                      --staging-files
                                                                      C:\Users\enric\AppData\Local\Temp\7z2A9FDEBC\sg

                         >>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
That looks like you have an antivirus or something similar blocking access to some of the files.

Can you:
1. Run the uninstaller https://github.com/diskuv/dkml-installer-ocaml/releases/download/v1.0.1/uninstall-diskuv-ocaml-windows_x86_64-1.0.1.exe
2. Temporarily disable your antivirus
3. Run the installer

**Comment by enricogoi** [comment]
Hello, 
 Thanks for looking into it. It was indeed something related to McAfee LiveSafe. Not sure which service exactly since I've turned off most of them. I've manage to successfully install ocaml.

**Comment by jonahbeckford** [comment]
Thanks. Closing, and documenting in the release notes about disabling anti-virus.
