### ISSUE TITLE
How to pass --enable-imprecise-c99-float-ops manually?

### ISSUE THREAD

**Issue by Kakadu** [diskuv/dkml-installer-ocaml#23]
Yes, I'm trying it inside virtualbox

**Comment by jonahbeckford** [comment]
If you look in the release notes https://gitlab.com/diskuv-ocaml/distributions/dkml/-/blob/main/contributors/changes/v1.1.0.md hopefully you can see:

```scheme
(
  (feature_flag_imprecise_c99_float_ops)
)
```

Write that as the file `$env:ProgramData\DiskuvOCaml\conf\ocamlcompiler.sexp` (inside virtualbox) before you run the installer.

There is an example of doing that in https://github.com/diskuv/dkml-installer-ocaml/blob/7fd94d46e1c41c6e1524819cbcc098ecec6380dc/vagrant/win32/test-language.ps1#L18-L23 which is used by a Vagrant CI (which uses VirtualBox on macOS to run Windows).

**Comment by Kakadu** [comment]
I tried to do that and it looks like that flag for disabling is passed explicitly, so enabling it back may depend on flags order. Also, I don't get meaning of `"$env:ProgramData\DiskuvOCaml\conf\ocamlcompiler.sexp" `, where it should be located?

See the screenshot (I renamed sexp -> sexp2 to temporary disable my setting and see that disabling flag is passed from somewhere else)

![image](https://user-images.githubusercontent.com/438226/210346292-1174da49-46f1-4d60-878a-73dcb0b8cfb8.png)

**Comment by Kakadu** [comment]
Also, after deinstallation it lefts some Diskuv-related directories. Is it normal?

![image](https://user-images.githubusercontent.com/438226/210347808-ebc6a82e-859c-47c2-99e8-5f72eb0667ac.png)

**Comment by jonahbeckford** [comment]
Weird how I missed that this ticket was still open. Sorry!

https://github.com/diskuv/dkml-installer-ocaml/issues/27 shows the technique does work. But it sounds like you may not know where your ProgramData folder is.

Can you open PowerShell in a brand new Virtual Box, and enter the .ps1 command exactly as I showed? That is line 21-23. Then tell me if that command failed.
(If it didn’t fail, go ahead and run the installer)

**Comment by jonahbeckford** [comment]
Ah. You need a mkdir first. See below.

Here is the full callout for the upcoming release (
https://gitlab.com/diskuv-ocaml/distributions/dkml/-/blob/cc5a524d85d90eb208211220ad25c8e420b28ac0/contributors/changes/v1.2.0.md ):

> Callout to **VirtualBox** users: You must do the following in a PowerShell terminal inside VirtualBox before running the installer:
> ```powershell
> mkdir C:\ProgramData\DiskuvOCaml\conf\
> Set-Content -Path "C:\ProgramData\DiskuvOCaml\conf\ocamlcompiler.sexp" -Value "((feature_flag_imprecise_c99_float_ops))"
> ```
