### ISSUE TITLE
pacman-key --init

### ISSUE THREAD

**Issue by jonahbeckford** [diskuv/dkml-installer-ocaml#26]
I have the same issue.  And if I try to run it again, it leads to this permission error because it tries to rebuild the bin files.  Even if I go in and leave msys installed and run `pacman-key --init` manually it still leads to the same problem.

_Originally posted by @tensor-programming

**Comment by jonahbeckford** [comment]
@tensor-programming, separating issues. Please update this issue with your results!

> Please Add Remove Programs, or use the uninstaller. Then rerun the installer.
>
> If you experience the same problem, please tell me approximately where you are located (ex. country). I can try to run a server in that region or country to see if it is a networking or route selection issue.

**Comment by tensor-programming** [comment]
Right, I did both of these things, but the uninstaller didn't properly remove all of the components, specifically the VS stuff which I already had installed on another instance.  I disagree that my issue is different from the other issue, its actually basically exactly what is being described in the other issue #25.

**Comment by jonahbeckford** [comment]
I think you were misunderstanding why I separated it out. I explained one big reason in the other issue, and the second reason is that the final troubleshooting option is to do a 1-on-1 Zoom call to see what is happening. So far, the 1-on-1 Zoom calls have had a 100% success rate even on deeply tricky issues.

Also, just in case I wasn't clear, I am waiting on answers to two questions.

*Status: Pending Requester Information*

**Comment by tensor-programming** [comment]
Right, I responded to your two questions in the other issue.

**Comment by jonahbeckford** [comment]
If you need a session with me, please use https://calendly.com/diskuv/30-minute-dkml-installation to schedule at your convenience.

**Comment by jonahbeckford** [comment]
Closing. Work completed and can be tracked in other issue
