### ISSUE TITLE
Broken links on the release page

### ISSUE THREAD

**Issue by apsheronets** [diskuv/dkml-installer-ocaml#29]
There: https://github.com/diskuv/dkml-installer-ocaml/releases
URLs must be contained "unsigned", not "setup".

**Comment by jonahbeckford** [comment]
While I prepare releases you will see a lot of "prerelease" releases. If testing passes, I sign them (which creates setup-*.exe and uninstall-*.exe), turn off GitHub's prerelease flag, and they become real releases.

I wish GitHub gave a way to not list "prerelease" releases on that page, but they do. Notice though that GitHub does show on the main page the latest real release.

- [ ] Perhaps using "draft" releases can fix this issue.

**Comment by jonahbeckford** [comment]
@apsheronets Please don't use any "prerelease" release. Those were all known to have bugs. I have erased all of them except the latest one (which will be erased in several hours).

**Comment by apsheronets** [comment]
Ok then. Sorry.

**Comment by jonahbeckford** [comment]
This was a good bug report. I'm still testing a fix to this, and if that works I'll close the ticket (even if it doesn't, I'll say that GitHub does not support what I'd like it to do, and then close the ticket).

So let's keep this open.

Thanks!

**Comment by jonahbeckford** [comment]
Okay, I have changed to "draft" releases and you should no longer see unreleased releases on that page.

Thanks for the issue!
