### ISSUE TITLE
Installed flexlink.exe cannot build executables without FLEXDIR set

### ISSUE THREAD

**Issue by jonahbeckford** [diskuv/dkml-installer-ocaml#40]
By default `flexlink.exe` looks for FlexDLL object files to link in the same directory as `flexlink.exe`. That behavior is defined by

https://github.com/ocaml/flexdll/blob/f5ccd9730d0766d0eb002cbe35a183f627044291/reloc.ml#L1407-L1428

FlexDLL object files `flexdll_initer_msvc64.obj` and `flexdll_msvc64.obj` (or 32-bit `_msvc` variant on 32-bit installs) must be installed alongside `$env:DiskuvOCamlHome/bin/flexlink.exe` so flexlink can be used standalone (it is in the PATH).

Previously only the OCaml linker, through its `flexdll_dirs = ["+flexdll"]` (ie. `<ocamlhome>/lib/ocaml/flexdll`) utils/config.ml setting, knew where the necessary FlexDLL `.obj` files were.

**Comment by ysalmon** [comment]
> FlexDLL object files ``flexdll_initer_msvc64.obj`` and ``flexdll_msvc64.obj``

But where are they ?

**Comment by jonahbeckford** [comment]
```powershell
C:\> Get-ChildItem -Recurse -Filter flexdll_msvc64.obj -Path $env:DiskuvOCamlHome

    Directory: C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\src\ocaml\flexdll


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          2/7/2023   2:40 AM          16832 flexdll_msvc64.obj

```

You don't need to use those files if you are using [`dkml init`](https://diskuv-ocaml.gitlab.io/distributions/dkml/doc/BeyondBasics.html) or `with-dkml`.

**Comment by jonahbeckford** [comment]
The Windows installer at Windows 64-bit Installer at https://gitlab.com/diskuv-ocaml/distributions/dkml/-/releases/1.2.1-10 has a correctly bundled flexdll.

Now it is:

```powershell
PS C:\Users\WDAGUtilityAccount> Get-ChildItem -Recurse -Filter flexdll_msvc64.obj -Path $env:DiskuvOCamlHome


    Directory: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\DiskuvOCaml\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          7/4/2023   1:48 AM          16844 flexdll_msvc64.obj


    Directory: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\DiskuvOCaml\lib\ocaml\flexdll


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          7/4/2023   1:48 AM          16844 flexdll_msvc64.obj
```

**Comment by jonahbeckford** [comment]
Major release https://discuss.ocaml.org/t/ann-dkml-2-0-0-preview-release/12642 closes this.
