### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by jimwellh** [diskuv/dkml-installer-ocaml#41]
Error message:
![image](https://user-images.githubusercontent.com/107164654/217153070-a52adfd2-5696-42d0-8f6f-c1b5cbe8e504.png)

Log file:
Github doesn't allow me to upload the .log file for some reason, but the message in the file is at below

> 2023-02-07T05:00:33.454Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\黃勁瑋\AppData\Local\Temp\PABCC3~1\0 clone https://github.com/thekid/inotify-win.git
Cloning into 'inotify-win'...
2023-02-07T05:00:33.980Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\黃勁瑋\AppData\Local\Temp\PABCC3~1\0\inotify-win -c advice.detachedHead=false checkout 36d18f3dfe042b21d7136a1479f08f0d8e30e2f9
HEAD is now at 36d18f3 Merge branch 'master' of github.com:thekid/inotify-win
2023-02-07T05:00:34.024Z [Win32] C:\WINDOWS\system32\cmd.exe /c call "C:\Users\黃勁瑋\AppData\Local\Temp\PABCC3~1\0\inotify-win\compile.bat"

> C:\Users\黃勁瑋\AppData\Local\Temp\7zEB01E830>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\   l޳\AppData\Local\Temp\PABCC3~1\0\inotify-win\inotifywait.exe" "C:\Users\   l޳\AppData\Local\Temp\PABCC3~1\0\inotify-win\src\*.cs" 

> '"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat"'` is not recognized as an internal or external command, operable program or batch file.
 
My system is:

- Device name LAPTOP-7QGE47E7
- Processor Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz
- Installed memory (RAM) 16.0 GB
- Device ID 1EB79096-F3A0-4C71-AC2C-420DE83ECC01
- Product Identification Number 00325-81441-58965-AAOEM
- System type 64-bit operating system, x64-type processor
- Stylus and touch This monitor does not offer stylus or touch input
- Version Windows 11 Home Edition
- Version 22H2
- Installed on ‎2022/‎9/‎22
- OS Build 22621.1105
- Serial number PF14G1HE
- Experience Windows Feature Experience Pack 1000.22638.1000.0

I've tried reboot the computer and run the installer as administrator but it gives the same error.

**Comment by jonahbeckford** [comment]
1. Can you run the "Visual Studio Installer" (press the Windows key, and then type "Visual Studio Installer")?
2. In the "Visual Studio Build Tools 2019", click More and then Repair. It should look something like:
    <img width="960" alt="image" src="https://user-images.githubusercontent.com/71855677/217300405-9bc03458-e753-4dd1-8cf2-2da26b060a05.png">
3. After the Repair, let's use a slightly newer installer: https://github.com/diskuv/dkml-installer-ocaml/releases/download/v1.2.1-prerel1/unsigned-diskuv-ocaml-windows_x86_64-i-1.2.0.exe

Tell me how that goes. (If that fails with the same error, in the "Visual Studio Build Tools 2019" you may need to click More and then Uninstall).

**Comment by jimwellh** [comment]
Hi,

I tried all the method you mentioned but the same error still pop up. 

the error message is:


C:\Users\黃勁瑋\AppData\Local\Temp\7z93240E54>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\���l޳\AppData\Local\Temp\PA904A~1\0\inotify-win\inotifywait.exe" "C:\Users\���l޳\AppData\Local\Temp\PA904A~1\0\inotify-win\src\*.cs"
error CS2021: file name 'C:\Users\���l޳\AppData\Local\Temp\PA904A~1\0\inotify-win\src\*.cs' is empty, contains invalid characters, specifies a drive but is not an absolute path, or is too long
error CS2001: source program file not found 'C:\Users\���l޳\AppData\Local\Temp\PA904A~1\0\inotify-win\src\*.cs'。
warning CS2008: no source files specified。
Setup did not complete because an error occurred.
Win32 command failed! Exited with 1. Command was: C:\WINDOWS\system32\cmd.exe /c call "C:\Users\黃勁瑋\AppData\Local\Temp\PA904A~1\0\inotify-win\compile.bat".

at Invoke-Win32CommandWithProgress, C:\Users\黃勁瑋\AppData\Local\Temp\7z93240E54\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 735
at <ScriptBlock>, C:\Users\黃勁瑋\AppData\Local\Temp\7z93240E54\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 878
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1





Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\黃勁瑋\AppData\Local\Programs\DISKUV~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\黃勁瑋\AppData\Local\Temp\7z93240E54\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\黃勁瑋\AppData\Local\Programs\DISKUV~1
                                             -OCamlLangVersion 4.14.0
                                             -MSYS2Dir
                                             C:\Users\黃勁瑋\AppData\Local\Programs\DISKUV~1\tools\MSYS2
                                             -OpamExe
                                             C:\Users\黃勁瑋\AppData\Local\Programs\DISKUV~1\bin\OPAM-R~1.EXE
                                             -DkmlPath
                                             C:\Users\黃勁瑋\AppData\Local\Temp\7Z9324~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -GlobalCompileDir
                                             C:\Users\黃勁瑋\AppData\Local\Temp\7Z9324~1\sg\STAGIN~1\generic
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\黃勁瑋\AppData\Local\Temp\PA904A~1
                                             -SkipProgress -SkipMSYS2Update

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\黃勁瑋\AppData\Local\Temp\7z93240E54\bin\dkml-install-user-runner.exe
                                         install-user-network-ocamlcompiler --verbosity=info
                                         --color=always --prefix
                                         C:\Users\黃勁瑋\AppData\Local\Programs\DiskuvOCaml
                                         --staging-files
                                         C:\Users\黃勁瑋\AppData\Local\Temp\7z93240E54\sg

                         >>> A transient failure occurred. <<<

**Comment by jimwellh** [comment]
I found this part in the command window
![image](https://user-images.githubusercontent.com/107164654/217416516-6400cc84-a7d1-4452-b457-6c668f4db79c.png)
There is a line 
`Path = C:\Users\���l޳\AppData\Local\Temp\7z5434D170\sg\offline-unixutils\windows_x86_64\bin\msys2-base.sfx.exe`
a bit weird since there is only public and 黃勁瑋 2 users in the Users file
![image](https://user-images.githubusercontent.com/107164654/217417557-66429b68-7322-4434-be07-9d96fb4fbecc.png)
I wonder if this is the part that triggers the error?

**Comment by jonahbeckford** [comment]
I highly suspect there are multiple parts of the installer that do not work with wide, perfectly valid Unicode characters like in 黃勁瑋.

This does need to get fixed ... it is important ... but since this needs a new test suite and CI machine it won't happen quickly. Sorry about that.

In the meantime can you look at the other Windows offerings at https://ocaml.org/docs/ocaml-on-windows?

**Comment by jonahbeckford** [comment]
Looks like this is not a Unicode problem but instead a `compile.bat` problem ... that filename triggers anti-virus/malware quarantines.

You can try the Windows 64-bit Installer at https://gitlab.com/diskuv-ocaml/distributions/dkml/-/releases/1.2.1-10 which completely removes the `compile.bat` step.

**Comment by jonahbeckford** [comment]
Major release https://discuss.ocaml.org/t/ann-dkml-2-0-0-preview-release/12642 closes this.
