### ISSUE TITLE
Trouble Installing OCaml in Windows

### ISSUE THREAD

**Issue by lolobabbins** [diskuv/dkml-installer-ocaml#45]
Hi! Yesterday I tried installing OCaml, but unfortunately my computer shut down halfway through, and now I'm running into various errors when trying to reinstall. I've deleted tried deleting the program files, along with the appdata of OCaml, however it has only caused me to run into new errors. I'd appreciate any help regarding this.

Currently, after deleting the appdata and rerunning the installer, I'm running into the following error:

2023-03-23T02:33:29.841Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\Eric\AppData\Local\Temp\PA26B7~1\0 clone https://github.com/thekid/inotify-win.git
Cloning into 'inotify-win'...
2023-03-23T02:33:30.357Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\Eric\AppData\Local\Temp\PA26B7~1\0\inotify-win -c advice.detachedHead=false checkout 36d18f3dfe042b21d7136a1479f08f0d8e30e2f9
HEAD is now at 36d18f3 Merge branch 'master' of github.com:thekid/inotify-win
2023-03-23T02:33:30.447Z [Win32] C:\WINDOWS\system32\cmd.exe /c call "C:\Users\Eric\AppData\Local\Temp\PA26B7~1\0\inotify-win\compile.bat"

C:\Users\Eric\AppData\Local\Temp\7z648B7AA0>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\Eric\AppData\Local\Temp\PA26B7~1\0\inotify-win\inotifywait.exe" "C:\Users\Eric\AppData\Local\Temp\PA26B7~1\0\inotify-win\src\*.cs" 
The system cannot find the path specified.

**Comment by jonahbeckford** [comment]
1. Can you go to the Control Panel and select `Add or remove programs`? You should be able to uninstall "Diskuv OCaml".
2. Then run Visual Studio Installer (press the Windows key, and then type it in). You will need to "More > Uninstall" (or "More > Repair") the `Visual Studio Build Tools 2019` installation.

Hopefully that will get you to a clean state where you can re-run the installer.

**Comment by jonahbeckford** [comment]
If it was `compile.bat` step that was failing, try the Windows 64-bit Installer at https://gitlab.com/diskuv-ocaml/distributions/dkml/-/releases/1.2.1-10
