### ISSUE TITLE
Diskuv installation failure

### ISSUE THREAD

**Issue by vengelson** [diskuv/dkml-installer-ocaml#48]
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: C:\Users\vaden\AppData\Local\Programs\DISKUV~1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 HOME=/home/vaden PATH=/clang64/bin:/usr/bin:/bin C:\Users\vaden\AppData\Local\Programs\DISKUV~1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/vaden/AppData/Local/Temp/PA9B39~1/0 C:\Users\vaden\AppData\Local\Programs\DISKUV~1\tools\MSYS2\usr\bin\env.exe DiskuvOCamlVarsVersion=2 DiskuvOCamlHome='/c/Users/vaden/AppData/Local/Programs/DISKUV~1'
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/11277608/setup-userprofile.full.log)
 
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/11277619/setup-userprofile.full.log)
DiskuvOCamlBinaryPaths='/c/Users/vaden/AppData/Local/Programs/DISKUV~1/usr/bin:/c/Users/vaden/AppData/Local/Programs/DISKUV~1/bin' DiskuvOCamlMSYS2Dir='/' DiskuvOCamlDeploymentId='v-1.2.0;ocaml-4.14.0;opam-2.2.0~alpha0~20221228;inotify-36d18f3dfe042b21d7136a1479f08f0d8e30e2f9;msys2-999CED2C8F5FF6A2;docker-99C8BC9860D703EB;bins-952D9673A6642899;stubs-4E6958B274EAB043;toplevels-80941AA1C64DA259' DiskuvOCamlVersion='1.2.0' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/vaden/AppData/Local/Temp/7Z18A4~1/sg/NETWOR~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop C:\Users\vaden\AppData\Local\Programs\DISKUV~1\tools\MSYS2\usr\bin\sh.exe /c/Users/vaden/AppData/Local/Temp/7z18A4B84C/sg/network-ocamlcompiler/windows_x86_64/install-ocaml.sh /c/Users/vaden/AppData/Local/Temp/7Z18A4~1/sg/NETWOR~1/WINDOW~1/dkmldir 15553b77175270d987058b386d737ccb939e8d5a windows_x86_64 /c/Users/vaden/AppData/Local/Programs/DISKUV~1 --disable-imprecise-c99-float-ops

at Invoke-MSYS2Command, C:\Users\vaden\AppData\Local\Temp\7z18A4B84C\sg\network-ocamlcompiler\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 165
at Invoke-MSYS2CommandWithProgress, C:\Users\vaden\AppData\Local\Temp\7z18A4B84C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 867
at <ScriptBlock>, C:\Users\vaden\AppData\Local\Temp\7z18A4B84C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 1138
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

[Advanced] MSYS2 commands can be run with: C:\Users\vaden\AppData\Local\Programs\DISKUV~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\vaden\AppData\Local\Programs\DISKUV~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\vaden\AppData\Local\Temp\7z18A4B84C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\vaden\AppData\Local\Programs\DISKUV~1
                                             -MSYS2Dir
                                             C:\Users\vaden\AppData\Local\Programs\DISKUV~1\tools\MSYS2
                                             -OpamExe
                                             C:\Users\vaden\AppData\Local\Programs\DISKUV~1\bin\OPAM-R~1.EXE
                                             -DkmlPath
                                             C:\Users\vaden\AppData\Local\Temp\7Z18A4~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -GlobalCompileDir
                                             C:\Users\vaden\AppData\Local\Temp\7Z18A4~1\sg\STAGIN~1\generic
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\vaden\AppData\Local\Temp\PA9B39~1
                                             -SkipProgress -SkipMSYS2Update

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\vaden\AppData\Local\Temp\7z18A4B84C\bin\dkml-install-user-runner.exe
                                         install-user-network-ocamlcompiler --verbosity=info
                                         --color=always --prefix
                                         C:\Users\vaden\AppData\Local\Programs\DiskuvOCaml
                                         --staging-files
                                         C:\Users\vaden\AppData\Local\Temp\7z18A4B84C\sg

                         >>> A transient failure occurred. <<<

Press "y" and ENTER to exit the installer.

**Comment by vengelson** [comment]
Attached log
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/11277622/setup-userprofile.full.log)

**Comment by jonahbeckford** [comment]
Are you using VirtualBox or some other virtualization?

Regardless, try:

1. https://github.com/diskuv/dkml-installer-ocaml/issues/31#issuecomment-1386215405
2. Go to Add/Remove programs to uninstall Diskuv OCaml
3. Re-run the installer.

**Comment by jonahbeckford** [comment]
This should have been mitigated, but wasn't verified by the reporter.
