### ISSUE TITLE
Set up Error FATAL [a0d16230].

### ISSUE THREAD

**Issue by ttraycie** [diskuv/dkml-installer-ocaml#50]
I keep gettng the below error during the set up and can't figure out why. Could you please help?

FATAL [a0d16230]. A transient failure occurred.

**Comment by jonahbeckford** [comment]
That isn't enough information. Can you copy and paste the last 2 pages of output? Or better yet, just attach the log file that it tells you about.

Thanks.

**Comment by jonahbeckford** [comment]
Closing; missing the log file.
