### ISSUE TITLE
The attribute cannot be set because attributes are not supported

### ISSUE THREAD

**Issue by fundid** [diskuv/dkml-installer-ocaml#56]
Installation fails at finalizing deployment

[output.log](https://github.com/diskuv/dkml-installer-ocaml/files/12061139/output.log)
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/12061137/setup-userprofile.full.log)

**Comment by jonahbeckford** [comment]
I believe this was fixed in #38 but is only available today in prereleases. Can you use https://gitlab.com/diskuv-ocaml/distributions/dkml/-/releases/1.2.1-10 ?

**Comment by fundid** [comment]
That worked, thank you
