### ISSUE TITLE
[ERROR] Failed to get sources of dkml-runtime-common-native.2.0.3: Bad checksum

### ISSUE THREAD

**Issue by jteg68** [diskuv/dkml-installer-ocaml#68]
Hi, trying installation with 2.0.3 native, it fails with the message below.
/Jörgen

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
[ERROR] Failed to get sources of dkml-runtime-common-native.2.0.3: Bad checksum
-> installed ocaml-system.4.14.0
-> installed ocaml-config.3
-> installed ocaml.4.14.0
System.Management.Automation.RemoteException
#=== ERROR while fetching sources for dkml-runtime-common-native.2.0.3 ========#
OpamSolution.Fetch_fail("https://gitlab.com/dkml/distributions/dkml/-/releases/2.0.3/downloads/src.dkml-runtime-common.tar.gz (Bad checksum, expected sha512=52052e5958f5f51000dc826d3c0a9bd5caa246b035aaaa915ace7a3f8414b39133cbc5adbee16e46b6179a08a3c8d2470540cd44f879f67d5d1c0271884952d0)")

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - fetch dkml-runtime-common-native 2.0.3
+-
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
| - install ocaml         4.14.0
| - install ocaml-config  3
| - install ocaml-system  4.14.0
[setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/12608231/setup-userprofile.full.log)

+-
# Run eval $(opam env '--root=C:\Users\XXX\AppData\Local\opam' --switch=playground) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [y/n] y
C:\Users\XXX\AppData\Local\opam\playground\OPAM-S~1\lock - The process cannot access the file because it is being used by another process.
System.Management.Automation.RemoteException
System.Management.Automation.RemoteException
========= [START OF TROUBLESHOOTING] ===========
System.Management.Automation.RemoteException
System.Management.Automation.RemoteException
Scroll up to see the [TROUBLESHOOTING] logs that begin at the [START OF TROUBLESHOOTING] line
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe MSYSTEM=CLANG64 MSYSTEM_PREFIX=/clang64 MSYSTEM_CARCH=x86_64 MSYSTEM_CHOST=x86_64-w64-mingw32 MINGW_CHOST=x86_64-w64-mingw32 MINGW_PACKAGE_PREFIX=mingw-w64-clang-x86_64 MINGW_PREFIX=/clang64 HOME=/home/XXX PATH=/clang64/bin:/usr/bin:/bin C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\usr\bin\env.exe PATH=/c/Program Files/Git/cmd:/clang64/bin:/usr/bin:/bin DKML_TMP_PARENTDIR=/c/Users/XXX/AppData/Local/Temp/PA98DA~1/0 env DiskuvOCamlVarsVersion=2 DiskuvOCamlDeploymentId='v-2.0.3;ocaml-4.14.0;opam-2.2.0~alpha0~20221228;msys2-F45581C12EA79770' DiskuvOCamlVersion='2.0.3' DiskuvOCamlMode='native' DiskuvOCamlHome='/c/Users/XXX/AppData/Local/Programs/DKMLNA~1' DiskuvOCamlBinaryPaths='/c/Users/XXX/AppData/Local/Programs/DKMLNA~1/usr/bin;/c/Users/XXX/AppData/Local/Programs/DKMLNA~1/bin' DiskuvOCamlMSYS2Dir='/' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR=/c/Users/SDUJOT/AppData/Local/Temp/7ZE749~1/sg/OCAMLC~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop C:\Users\XXX\AppData\Local\Temp\7ZE749~1\sg\OCAMLC~1\WINDOW~1\dkmldir\vendor\drd\src\unix\create-opam-switch.sh -p windows_x86_64 -y -w -n playground -v /c/Users/XXX/AppData/Local/Programs/DKMLNA~1 -o C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\bin\OPAM-R~1.EXE -e PKG_CONFIG_PATH=C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\clang64\lib\pkgconfig -e PKG_CONFIG_SYSTEM_INCLUDE_PATH= -e PKG_CONFIG_SYSTEM_LIBRARY_PATH= -m conf-withdkml -e PKG_CONFIG_PATH=C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\clang64\lib\pkgconfig

at Invoke-MSYS2Command, C:\Users\XXX\AppData\Local\Temp\7zE749A684\sg\ocamlcompiler-common\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 180
at Invoke-GenericCommandWithProgress, C:\Users\XXX\AppData\Local\Temp\7zE749A684\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 841
at <ScriptBlock>, C:\Users\XXX\AppData\Local\Temp\7zE749A684\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.ps1: line 1257
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

[Advanced] MSYS2 commands can be run with: C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\XXX\AppData\Local\Temp\7zE749A684\sg\ocamlcompiler-common\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\XXX\AppData\Local\Programs\DKMLNA~1
                                             -OCamlLangVersion 4.14.0
                                             -DkmlPath
                                             C:\Users\XXXAppData\Local\Temp\7ZE749~1\sg\OCAMLC~1\WINDOW~1\dkmldir
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\XXX\AppData\Local\Temp\PA98DA~1
                                             -SkipProgress -SkipMSYS2Update
                                             -OpamExe
                                             C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\bin\OPAM-R~1.EXE
                                             -MSYS2Dir
                                             C:\Users\XXX\AppData\Local\Programs\DKMLNA~1\tools\MSYS2

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\XXX\AppData\Local\Temp\7zE749A684\bin\dkml-install-user-runner.exe
                                         install-user-ocamlcompiler-network --verbosity=info
                                         --color=always --prefix
                                         C:\Users\XXX\AppData\Local\Programs\DkMLNative
                                         --staging-files
                                         C:\Users\XXX\AppData\Local\Temp\7zE749A684\sg

                         >>> A transient failure occurred. <<<

Press "y" and ENTER to exit the installer.

**Comment by jonahbeckford** [comment]
Fixing ...

**Comment by jonahbeckford** [comment]
Verified.

Please re-run your installer (you should not need to re-download it). Thanks for your patience.

**Comment by jteg68** [comment]
Thanks, working now.
