### ISSUE TITLE
dkml bytecode installation on windows, can not deinstall

### ISSUE THREAD

**Issue by roromino** [diskuv/dkml-installer-ocaml#85]
I have installed dkml bytecode installation on windows. I have nothing more, and now I try to deinstall (using windows app deinstall menu) and get : 

FATAL [14b63c08]. The component 'ocamlcompiler-offline' declares a dependency on 'ocamlcompiler-common' but that component is not available. Check the following in order: 1) Has `dkml-component-ocamlcompiler-common` been added as an Opam (or findlib) dependency? 2) Does `dkml-component-ocamlcompiler-common` call [Registry.add_component] using [component_name="ocamlcompiler-common"]? 3) Is there a `META.dkml-component-ocamlcompiler-offline.template` with either an `install_depends_on` or `uninstall_depends_on` space separated option that includes `ocamlcompiler-common`?

Press "y" and ENTER to exit the uninstaller.

thank you

**Comment by jonahbeckford** [comment]
When DkML 2.1.0 is released (it will no longer say "Upcoming release"), you will not need the Bytecode edition. So:
1. Wait for DkML 2.1.0 (#84) and then install it.
2. Open Windows Explorer, navigate to the folder `%LOCALAPPDATA%\Programs`, and delete the `DkMLByte` folder

**Comment by roromino** [comment]
thank you
