### ISSUE TITLE
MSYS2 command failed when install.

### ISSUE THREAD

**Issue by diantaowang** [diskuv/dkml-installer-ocaml#9]
## Description
When I installed OCaml, I encountered some problems that caused the installation to fail, which seems to be caused by MSYS2. Thanks!
## Environment
* Windows 10: Version 21H1 (OS Build 19043.1645)
* MSVC 2019
## Error Message
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: export DKML_TMP_PARENTDIR='/c/Users/diawan01/AppData/Local/Temp/PAD3D5~1/0' && export PATH='/c/Program Files/Git/cmd':"$PATH" && env DiskuvOCamlVarsVersion=2 DiskuvOCamlHome='/c/Users/diawan01/AppData/Local/Programs/DISKUV~1/0' DiskuvOCamlBinaryPaths='/c/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/usr/bin:/c/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/bin' DiskuvOCamlMSYS2Dir='/' DiskuvOCamlDeploymentId='v-1.0.1;ocaml-4.12.1;opam-2.2.0~alpha~dev;inotify-36d18f3dfe042b21d7136a1479f08f0d8e30e2f9;msys2-999CED2C8F5FF6A2;docker-B01818D2C9F9286A;pkgs-41F2F26E25F649A6;bins-A13EC471D2E2F24D;stubs-4E6958B274EAB043;toplevels-80941AA1C64DA259' DiskuvOCamlVersion='1.0.1' WITHDKML_ENABLE=OFF OCAMLLIB= TOPDIR='/c/Users/diawan01/AppData/Local/Temp/7ZC0F0~1/sg/NETWOR~1/WINDOW~1/dkmldir/vendor/drc/all/emptytop' /opt/diskuv-ocaml/installtime/private/install-ocaml.sh '/c/Users/diawan01/AppData/Local/Temp/7ZC0F0~1/sg/NETWOR~1/WINDOW~1/dkmldir' 46c947827ec2f6d6da7fe5e195ae5dda1d2ad0c5 windows_x86_64 '/c/Users/diawan01/AppData/Local/Programs/DISKUV~1/0'

at Invoke-MSYS2Command, C:\Users\diawan01\AppData\Local\Temp\7zC0F03438\sg\network-ocamlcompiler\windows_x86_64\dkmldir\vendor\drd\src\windows\UnixInvokers\UnixInvokers.psm1: line 152
at Invoke-MSYS2CommandWithProgress, C:\Users\diawan01\AppData\Local\Temp\7zC0F03438\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 822
at <ScriptBlock>, C:\Users\diawan01\AppData\Local\Temp\7zC0F03438\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 1166
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

[Advanced] MSYS2 commands can be run with: C:\Users\diawan01\AppData\Local\Programs\DISKUV~1\tools\MSYS2\msys2_shell.cmd

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\diawan01\AppData\Local\Programs\DISKUV~1\0\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\diawan01\AppData\Local\Temp\7zC0F03438\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\diawan01\AppData\Local\Programs\DISKUV~1
                                             -MSYS2Dir
                                             C:\Users\diawan01\AppData\Local\Programs\DISKUV~1\tools\MSYS2
                                             -OpamBinDir
                                             C:\Users\diawan01\AppData\Local\Temp\PAD3D5~1\opam
                                             -DkmlPath
                                             C:\Users\diawan01\AppData\Local\Temp\7ZC0F0~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -DkmlHostAbi windows_x86_64
                                             -TempParentPath
                                             C:\Users\diawan01\AppData\Local\Temp\PAD3D5~1
                                             -SkipProgress

\>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.
                         Root cause: The command had exit code 20:
                                                                    C:\Users\diawan01\AppData\Local\Temp\7zC0F03438\bin\dkml-install-user-runner.exe
                                                                      install-user-network-ocamlcompiler
                                                                      --verbosity=info --color=always
                                                                      --prefix
                                                                      C:\Users\diawan01\AppData\Local\Programs\DiskuvOCaml
                                                                      --staging-files
                                                                      C:\Users\diawan01\AppData\Local\Temp\7zC0F03438\sg
                         >>> A transient failure occurred. <<<

Press "y" and ENTER to exit the installer.

**Comment by diantaowang** [comment]
## Partial Log
File "C:\Users\diawan01\AppData\Local\Programs\DiskuvOCaml\0\src\ocaml\stdlib\ephemeron.ml", line 1:
Error: I/O error: Permission denied
make: *** [Makefile:216: stdlib__ephemeron.cmx] Error 2
make: *** Waiting for unfinished jobs....
make: Leaving directory '/c/Users/diawan01/AppData/Local/Programs/DiskuvOCaml/0/src/ocaml/stdlib'
FATAL: make -j8 -l8 CAMLDEP=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/runtime/ocamlrun.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/ocamlc.exe -depend CAMLLEX=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/runtime/ocamlrun.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/lex/ocamllex.exe OCAMLLEX=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/runtime/ocamlrun.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/lex/ocamllex.exe CAMLYACC=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/yacc/ocamlyacc.exe OCAMLYACC=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/yacc/ocamlyacc.exe CAMLRUN=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/runtime/ocamlrun.exe OCAMLRUN=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/runtime/ocamlrun.exe CAMLC=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/env.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/ocamlcHost-compile-stdlib.wrapper OCAMLC=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/env.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/ocamlcHost-compile-stdlib.wrapper CAMLOPT=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/env.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/ocamloptHost-compile-stdlib.wrapper OCAMLOPT=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/env.exe C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/support/ocamloptHost-compile-stdlib.wrapper OCAMLDOC_RUN=C:/Users/diawan01/AppData/Local/Programs/DiskuvOCaml/tools/MSYS2/usr/bin/env.exe CAML_LD_LIBRARY_PATH=C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/otherlibs/win32unix:C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/otherlibs/str C:/Users/diawan01/AppData/Local/Programs/DISKUV~1/0/src/ocaml/ocamldoc/ocamldoc.exe NATDYNLINK=true NATDYNLINKOPTS= -C stdlib allopt failed
@ERR+ utils/config.ml
@config.ml+| #2 "utils/config.mlp"
@config.ml+| (**************************************************************************)
@config.ml+| (*                                                                        *)
@config.ml+| (*                                 OCaml                                  *)
@config.ml+| (*                                                                        *)
@config.ml+| (*             Xavier Leroy, projet Cristal, INRIA Rocquencourt           *)
@config.ml+| (*                                                                        *)
@config.ml+| (*   Copyright 1996 Institut National de Recherche en Informatique et     *)
@config.ml+| (*     en Automatique.                                                    *)
@config.ml+| (*                                                                        *)
@config.ml+| (*   All rights reserved.  This file is distributed under the terms of    *)
@config.ml+| (*   the GNU Lesser General Public License version 2.1, with the          *)
@config.ml+| (*   special exception on linking described in the file LICENSE.          *)
@config.ml+| (*                                                                        *)
@config.ml+| (**************************************************************************)

**Comment by jonahbeckford** [comment]
Sorry I didn't see this earlier! I missed the email notification.

The `Error: I/O error: Permission denied` is likely due to your anti-virus blocking access to some files, or you are running out of disk space. Please temporarily disable your anti-virus during the install, and double-check you have lots of disk space.

If that doesn't fix your issue, you can setup a Zoom video call at https://calendly.com/diskuv/60min-install .

**Comment by LouisClt** [comment]
Hello, I think I have the same problem. I tried running it without any anti-virus, but it did not change anything.
The error message seems to be the same, but before that I have : 
```
========= [TROUBLESHOOTING] ocaml-system-71408-2bcd70.out ===========

[ocaml-system-71408-2bcd70.out] File "command line", line 1:
[ocaml-system-71408-2bcd70.out] Error: Unbound module Stdlib

Scroll up to see the [TROUBLESHOOTING] logs that begin at the [START OF TROUBLESHOOTING] line
Setup did not complete because an error occurred.
MSYS2 command failed! Exited with 107. Command was: export DKML_TMP_PARENTDIR='/ [...]
```
`Error: Unbound module Stdlib` That problem seems to be linked to incorrect version of compiler corresponding to the code.

( There is another problem afterwards when I try to re-install the code (but that is another problem) ; 

```
2022-11-09T20:20:56.921Z Cleaning directory C:\Users\louis\AppData\Local\Programs\DiskuvOCaml\0 ...
Set-ItemProperty : Impossible de définir l’attribut, car les attributs ne sont pas pris en charge. Seuls les attributs suivants peuvent être définis :
Archive, Hidden, Normal, ReadOnly ou System.
Au caractère C:\Users\louis\AppData\Local\Temp\7z4A04CEBC\sg\network-ocamlcompiler\windows_x86_64\SingletonInstall\Deployers\Deployers.psm1:508 : 13
+             Set-ItemProperty -Path $_.FullName -Name Attributes -Valu ...
+          
```

)

**Comment by jonahbeckford** [comment]
Closing since aged out without a response. Re-open if this still needs engagement.
