### ISSUE TITLE
Diskuv Error FATAL [54c34807]  [ERROR] FATAL [5f927a8b].

### ISSUE THREAD

**Issue by ilyes256** [diskuv/dkml-installer-ocaml#94]
windows_install.bc: [INFO] C:\Users\ilyes\AppData\Local\Temp\7zB57CF374\sg\offline-unixutils\windows_x86_64\bin\msys2-base.sfx.exe ran successfully
FATAL [54c34807]. move C:\Users\ilyes\AppData\Local\Programs\DiskuvOCaml\tools\msys64 to C:\Users\ilyes\AppData\Local\Programs\DiskuvOCaml\tools\MSYS2: Permission denied

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\ilyes\AppData\Local\Temp\7zB57CF374\bin\dkml-install-user-runner.exe
                                         install-user-offline-unixutils --verbosity=info
                                         --color=always --prefix
                                         C:\Users\ilyes\AppData\Local\Programs\DiskuvOCaml
                                         --staging-files
                                         C:\Users\ilyes\AppData\Local\Temp\7zB57CF374\sg

                         >>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
I can't tell from your issue but I think you may be using an old installer.

Can you use https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.0 ?
