### ISSUE TITLE
FATAL [a0d16230] & FATAL [5f927a8b] error due to no path specification according to the installer

### ISSUE THREAD

**Issue by step4upp** [diskuv/dkml-installer-ocaml#95]
The followings are the errors that I got from the installation.
I already removed diskuv ocaml once before and recently I tried to reinstall but the constant error comes out.
The followings are the errors that I got from the installation prompt.

2024-01-22T00:56:23.174Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\ccyym\AppData\Local\Temp\PA8981~1\0 clone https://github.com/thekid/inotify-win.git
Cloning into 'inotify-win'...
2024-01-22T00:56:25.389Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\ccyym\AppData\Local\Temp\PA8981~1\0\inotify-win -c advice.detachedHead=false checkout 36d18f3dfe042b21d7136a1479f08f0d8e30e2f9
HEAD is now at 36d18f3 Merge branch 'master' of github.com:thekid/inotify-win
2024-01-22T00:56:25.502Z [Win32] C:\WINDOWS\system32\cmd.exe /c call "C:\Users\ccyym\AppData\Local\Temp\PA8981~1\0\inotify-win\compile.bat"

C:\Users\ccyym\AppData\Local\Temp\7z47B34D7C>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\ccyym\AppData\Local\Temp\PA8981~1\0\inotify-win\inotifywait.exe" "C:\Users\ccyym\AppData\Local\Temp\PA8981~1\0\inotify-win\src\*.cs" 
The system cannot find the path specified.
Setup did not complete because an error occurred.
Win32 command failed! Exited with 1. Command was: C:\WINDOWS\system32\cmd.exe /c call "C:\Users\ccyym\AppData\Local\Temp\PA8981~1\0\inotify-win\compile.bat".

at Invoke-Win32CommandWithProgress, C:\Users\ccyym\AppData\Local\Temp\7z47B34D7C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 771
at <ScriptBlock>, C:\Users\ccyym\AppData\Local\Temp\7z47B34D7C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 914
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

Bug Reports can be filed at https://github.com/diskuv/dkml-installer-ocaml/issues
Please copy the error message and attach the log file available at
  C:\Users\ccyym\AppData\Local\Programs\DISKUV~1\setup-userprofile.full.log

FATAL [a0d16230]. A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\ccyym\AppData\Local\Temp\7z47B34D7C\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\ccyym\AppData\Local\Programs\DISKUV~1
                                             -MSYS2Dir
                                             C:\Users\ccyym\AppData\Local\Programs\DISKUV~1\tools\MSYS2
                                             -OpamExe
                                             C:\Users\ccyym\AppData\Local\Programs\DISKUV~1\bin\OPAM-R~1.EXE
                                             -DkmlPath
                                             C:\Users\ccyym\AppData\Local\Temp\7Z47B3~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -GlobalCompileDir
                                             C:\Users\ccyym\AppData\Local\Temp\7Z47B3~1\sg\STAGIN~1\generic
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\ccyym\AppData\Local\Temp\PA8981~1
                                             -SkipProgress -SkipMSYS2Update

>>> A transient failure occurred. <<<

dkml-package.bc: [ERROR] FATAL [5f927a8b].
                         A transient failure occurred.

                         Root cause: The command had exit code 20:
                                       C:\Users\ccyym\AppData\Local\Temp\7z47B34D7C\bin\dkml-install-user-runner.exe
                                         install-user-network-ocamlcompiler --verbosity=info
                                         --color=always --prefix
                                         C:\Users\ccyym\AppData\Local\Programs\DiskuvOCaml
                                         --staging-files
                                         C:\Users\ccyym\AppData\Local\Temp\7z47B34D7C\sg

                         >>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
Can you use https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.0 ?

**Comment by step4upp** [comment]
The installation came out to complete but the following error came out when I ran 'opam init'.

FATAL: No Common7/Tools/VsDevCmd.bat was detected at /c/DiskuvOCaml/BuildTools
FATAL: Compiler autodetection failed with exit code 107

**Comment by jonahbeckford** [comment]
Should have sent you directly to the instructions at https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.0#new-install-steps

TLDR:

```sh
winget install Microsoft.VisualStudio.2019.BuildTools --override "--wait --passive --installPath C:\VS --addProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
winget install Git.Git
winget install Diskuv.OCaml
```

And then in a new terminal:

```sh
dkml init --system
```

**Comment by step4upp** [comment]
Sorry, I should have read the instructions thoroughly.

This is the other error from running 'dkml init --system'.
It keeps returning the error code 107.

dkml.exe: [WARNING] Detected that a Visual Studio compatible with DkML has not been located. Locating it now. ETA: 1 minute.
Configuring DkML to use the compatible Visual Studio found at: C:\DiskuvOCaml\BuildTools
dkml.exe: [WARNING] Detected that the system native code OCaml compiler is not present. Creating it now. ETA: 15 minutes.
[2024-01-22T01:36:26+00:00] C:\Users\ccyym\AppData\Local\Temp\dkml-initsystem-de-75145e\scripts/vendor/dkml-compiler/src/r-c-ocaml-1-setup.sh
[2024-01-22T01:36:29+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml fsck --strict --no-dangling --no-progress
[2024-01-22T01:36:30+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml rev-parse HEAD
[2024-01-22T01:36:30+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml stash
No local changes to save
[2024-01-22T01:36:30+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml reset --hard 15553b77175270d987058b386d737ccb939e8d5a
HEAD is now at 15553b7 release 4.14.0
[2024-01-22T01:36:30+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml submodule update --init --recursive
[2024-01-22T01:36:31+00:00] /usr/bin/chmod
[2024-01-22T01:36:33+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml clean -d -x -f
Removing msvs-detect
[2024-01-22T01:36:33+00:00] git -C C:/Users/ccyym/AppData/Local/Programs/DKMLNA~1/src/ocaml submodule foreach --recursive git clean -d -x -f -
Entering 'flexdll'
FATAL: No Common7/Tools/VsDevCmd.bat was detected at /c/DiskuvOCaml/BuildTools
dkml: FATAL: <builtin>\install-ocaml-compiler.sh exited with error code 107

**Comment by jonahbeckford** [comment]
Okay, the `winget install Microsoft.VisualStudio.2019.BuildTools --override "--wait --passive --installPath C:\VS --addProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"`

was instructions to install Visual Studio at `C:\VS`. And your error is complaining it is looking in `C:\DiskuvOCaml\BuildTools` (an old location). So you are in a messy middle state.

Can you run "Visual Studio Installer" (press Windows key and type "Visual Studio Installer") and then delete the "Visual Studio Build Tools 2019"? You might have one or two at this point. Delete them both.

Then rerun:

```
winget install Microsoft.VisualStudio.2019.BuildTools --override "--wait --passive --installPath C:\VS --addProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
```

so only one version is on your PC.

I may hold an office hours Monday (tomorrow for me) if you still have problems. So if you have problems, tell me a time and I'll try to accommodate (I'm in the Pacific timezone).

**Comment by step4upp** [comment]
Thank you so much!
Initialization was successful!
The dkml is running without any problem now!
