### ISSUE TITLE
Windows fatal error [a0d16230].

### ISSUE THREAD

**Issue by Valionux** [diskuv/dkml-installer-ocaml#96]
FATAL [setup-userprofile.full.log](https://github.com/diskuv/dkml-installer-ocaml/files/14132399/setup-userprofile.full.log) A transient failure occurred.

Root cause: The conformant command had exit code 1:
                                           C:\Users\taoya\AppData\Local\Temp\7z9EB57620\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.bat
                                             -AllowRunAsAdmin
                                             -InstallationPrefix
                                             C:\Users\taoya\AppData\Local\Programs\DISKUV~1
                                             -MSYS2Dir
                                             C:\Users\taoya\AppData\Local\Programs\DISKUV~1\tools\MSYS2
                                             -OpamExe
                                             C:\Users\taoya\AppData\Local\Programs\DISKUV~1\bin\OPAM-R~1.EXE
                                             -DkmlPath
                                             C:\Users\taoya\AppData\Local\Temp\7Z9EB5~1\sg\NETWOR~1\WINDOW~1\dkmldir
                                             -GlobalCompileDir
                                             C:\Users\taoya\AppData\Local\Temp\7Z9EB5~1\sg\STAGIN~1\generic
                                             -NoDeploymentSlot -DkmlHostAbi
                                             windows_x86_64 -TempParentPath
                                             C:\Users\taoya\AppData\Local\Temp\PA3782~1
                                             -SkipProgress -SkipMSYS2Update

>>> A transient failure occurred. <<<

**Comment by jonahbeckford** [comment]
I think you may be using an old installer. There are new instructions at https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.0#new-install-steps

TLDR:

```sh
winget install Microsoft.VisualStudio.2019.BuildTools --override "--wait --passive --installPath C:\VS --addProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
winget install Git.Git
winget install Diskuv.OCaml
```

And then in a new terminal:

```sh
dkml init --system
```
