### ISSUE TITLE
OCaml not getting installed on windows

### ISSUE THREAD

**Issue by mridulsrivastavaa** [diskuv/dkml-installer-ocaml#99]
Setup did not complete because an error occurred.
Win32 command failed! Exited with 1. Command was: C:\WINDOWS\system32\cmd.exe /c call "C:\Users\HP\AppData\Local\Temp\PA19DC~1\0\inotify-win\compile.bat".

at Invoke-Win32CommandWithProgress, C:\Users\HP\AppData\Local\Temp\7z5822BFA0\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 771
at <ScriptBlock>, C:\Users\HP\AppData\Local\Temp\7z5822BFA0\sg\network-ocamlcompiler\windows_x86_64\setup-userprofile.ps1: line 914
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

2024-03-06T16:45:23.801Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\HP\AppData\Local\Temp\PA19DC~1\0 clone https://github.com/thekid/inotify-win.git
Cloning into 'inotify-win'...
2024-03-06T16:45:26.480Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\HP\AppData\Local\Temp\PA19DC~1\0\inotify-win -c advice.detachedHead=false checkout 36d18f3dfe042b21d7136a1479f08f0d8e30e2f9
HEAD is now at 36d18f3 Merge branch 'master' of github.com:thekid/inotify-win
2024-03-06T16:45:26.568Z [Win32] C:\WINDOWS\system32\cmd.exe /c call "C:\Users\HP\AppData\Local\Temp\PA19DC~1\0\inotify-win\compile.bat"

C:\Users\HP\AppData\Local\Temp\7z5822BFA0>"C:\DiskuvOCaml\BuildTools\Common7\Tools\vsdevcmd.bat" -no_logo -vcvars_ver=14.26 -winsdk=10.0.18362.0   && csc.exe /nologo /target:exe "/out:C:\Users\HP\AppData\Local\Temp\PA19DC~1\0\inotify-win\inotifywait.exe" "C:\Users\HP\AppData\Local\Temp\PA19DC~1\0\inotify-win\src\*.cs" 
The system cannot find the path specified.

**Comment by jonahbeckford** [comment]
Apologies. Haven't updated the main ocaml.org page yet with the new instructions.

---

There are new instructions at https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.0#new-install-steps

TLDR:

```sh
winget install Microsoft.VisualStudio.2019.BuildTools --override "--wait --passive --installPath C:\VS --addProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
winget install Git.Git
winget install Diskuv.OCaml
```

And then in a new terminal:

```sh
dkml init --system
```

**Comment by mridulsrivastavaa** [comment]
> Apologies. Haven't updated the main ocaml.org page yet with the new instructions.
> 
> There are new instructions at https://gitlab.com/dkml/distributions/dkml/-/releases/2.1.0#new-install-steps
> 
> TLDR:
> 
> ```shell
> winget install Microsoft.VisualStudio.2019.BuildTools --override "--wait --passive --installPath C:\VS --addProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
> winget install Git.Git
> winget install Diskuv.OCaml
> ```
> 
> And then in a new terminal:
> 
> ```shell
> dkml init --system
> ```

Thank you. This worked.
